identifier="MoneyFactory:Outoine15"
name="Money Factory"
description="Adds a selling station to transform the most valuable items into Money and a buying station to spend it."
authors=["Outoine15"]
dependencies=["VoxelEras:DestinyHailstorm"]
entry="money_factory/entry.rhai"
version="1.0.4d1"
sync=true