fn define(mod_info){
    mod_info.add(TextureBuilder(
        "moneyOutputIcon:MoneyFactory",
        "money_factory/assets/MoneyIcon/MoneyOutputIcon.png"
    ));
    mod_info.add(TextureBuilder(
        "autoSellPointIcon:MoneyFactory",
        "money_factory/assets/textures/autoSellPointOff.png"
    ));
    mod_info.add(TextureBuilder(
        "smolGeneralStoreIcon:MoneyFactory",
        "money_factory/assets/textures/smol_general_store.png"
    ))
}